version: "3.9"
services:

  php:
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8000:8000
    # depends_on:
    #   - mysql
    #   - adminer

  # node:
  #   build:
  #     context: .
  #     target: node

  #   volumes:
  #     - ./:/usr/src
  #     - ./node_modules:/usr/src/node_modules
  #   tty: true

  #   ports:
  #     - 5173:5173

#   mysql:
#     image: mariadb:10.8.3
#     # Uncomment below when on Mac M1
#     # platform: linux/arm64/v8
#     command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     environment:
#       - MYSQL_DATABASE=${DB_DATABASE}
#       - MYSQL_USER=${DB_USERNAME}
#       - MYSQL_PASSWORD=${DB_PASSWORD}
#       - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
#     ports:
#       - 3306:3306

  # adminer:

  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
